[cibuildwheel]
build = "cp39-* cp310-* cp311-* cp312-*"
skip = "pp* *-musllinux*"
build-verbosity = 1
test-command = "python -c \"import rdkit; print(rdkit.__version__)\""

[cibuildwheel.linux]
archs = ["x86_64"]

[cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[cibuildwheel.windows]
archs = ["AMD64"]
